<dune_plugin_update_info>
    <schema>2</schema>
    <name>%name%</name>
    <plugin_version_descriptor>
        <version_index>%version_index%</version_index>
        <version>%version%</version>
        <beta>yes</beta>
        <critical>%critical%</critical>
        <url>%update_url%dune_plugin_%version_index%.tgz</url>
        <md5>%tgz_md5%</md5>
        <size>%size%</size>
        <caption>%caption%</caption>
    </plugin_version_descriptor>
</dune_plugin_update_info>
